### ISSUE TITLE
Errors building sdl2

### ISSUE THREAD

**Issue by hsdk123** [mosra/toolchains#9]
Hi, I'm trying to build sdl2 from sources here:  https://github.com/SDL-mirror/SDL
The cmake config goes fine with the ios toolchain, but builds fail complaining about missing headers, etc.

I use the following steps:
```
mkdir build-ios && cd build-ios
cmake .. \
    -DCMAKE_TOOLCHAIN_FILE=../toolchains/generic/iOS.cmake \
    -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk \
    -DCMAKE_OSX_ARCHITECTURES="arm64;armv7;armv7s" \
    -DCMAKE_INSTALL_PREFIX=~/ios-libs \
    -G Xcode
cmake --build .
```

**Comment by mosra** [comment]
I never tried this, actually -- IIRC the CMake build is kinda half-done, with particular platforms still having their own buildsystems. You're better off using the officially documented way to build it using the Xcode project they provide. This is how I do it on the CI: https://github.com/mosra/magnum/blob/34261840bc6b2c3e1bf3899605bb638ff687a0ff/package/ci/travis.yml#L232

What I hope for is that at some point SDL will be usable as a CMake subproject. But there's a long way to go, apparently -- ~~https://twitter.com/slurpsmadrips/status/1175866419906408450 (from September, not aware of any new developments on this front)~~ https://twitter.com/icculus/status/1212448451830702080. Until then, I'm pretending SDL is not usable with CMake :)

EDIT: updated a link with current state (Jan 1st, 2020 -- nothing new since September 2019)

**Comment by hsdk123** [comment]
Ah, gotcha, and thanks for the CI reference! The cmakelists file that's inside the git repo seemed to be working for Windows, Mac, and Android, and so I was hoping it would also work for iOS. Would be nice if SDL would become a github repository at some point.
